# Generated by Django 4.1.2 on 2022-10-19 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('td_id', models.SmallIntegerField()),
                ('username', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=255)),
                ('admins', models.ManyToManyField(related_name='admins', to='bot.person')),
                ('persons', models.ManyToManyField(related_name='persons', to='bot.person')),
            ],
        ),
        migrations.CreateModel(
            name='RoomRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=0)),
                ('required_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.person')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.room')),
            ],
        ),
        migrations.CreateModel(
            name='Fuckup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=455)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.person')),
                ('category', models.ForeignKey(default='Косяк', on_delete=django.db.models.deletion.SET_DEFAULT, to='bot.category')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.room')),
            ],
        ),
    ]
