# Generated by Django 4.1.2 on 2022-10-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_fuckup_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='td_id',
        ),
        migrations.AddField(
            model_name='person',
            name='tg_id',
            field=models.SmallIntegerField(null=True, unique=True),
        ),
    ]
