# Generated by Django 4.1.2 on 2022-10-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_remove_person_td_id_person_tg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='current_room_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
