# Generated by Django 4.1.2 on 2022-10-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_person_current_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='admins',
            field=models.ManyToManyField(null=True, related_name='admins', to='bot.person'),
        ),
        migrations.AlterField(
            model_name='room',
            name='persons',
            field=models.ManyToManyField(null=True, related_name='persons', to='bot.person'),
        ),
    ]
