# Generated by Django 4.1.2 on 2022-10-22 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_category_tittle_alter_room_admins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='room',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='bot.room'),
            preserve_default=False,
        ),
    ]
