# Generated by Django 4.1.2 on 2022-10-22 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_category_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomrequest',
            name='is_required',
        ),
    ]
